In [43]:
#1-1
from sympy import *
x = Symbol('x') 
N = Symbol('N')
print("1.1 ")
print(integrate(x**10),(x,0,N))

1.1 
x**11/11 (x, 0, N)


In [44]:
#1-2
from sympy import *
x = Symbol('x') 
N = Symbol('N')
print("1.02: ")
Sum(x**10,(x,0,N)).doit()

1.02: 


N**11/11 + N**10/2 + 5*N**9/6 - N**7 + N**5 - N**3/2 + 5*N/66

In [45]:
#1-3
from sympy import *
x = Symbol('x') 
N = Symbol('N')
print("1.03: ")
Sum((x-1)**10,(x,0,N)).doit()

1.03: 


N**11/11 - N**10/2 + 5*N**9/6 - N**7 + N**5 - N**3/2 + 5*N/66 + 1

In [46]:
#1-4
from sympy import *
x = Symbol('x') 
e = Symbol('e') 
print("1.04: ")
print(integrate(x**10*exp(-x)),(x,0,oo))

1.04: 
(-x**10 - 10*x**9 - 90*x**8 - 720*x**7 - 5040*x**6 - 30240*x**5 - 151200*x**4 - 604800*x**3 - 1814400*x**2 - 3628800*x - 3628800)*exp(-x) (x, 0, oo)


In [47]:
#1-5
from sympy import *
import matplotlib.pyplot as plt
x = Symbol('x')
y = Symbol('y')
f = exp(-((x-1)**2+(y+1)**2))
f1 = diff(f,x)
f2 = diff(f,y)
f3 = diff(f1,y)
print("1.05: ")
print(f1)
print(f2)
print(f3)
#1-6
print("1-6: ",solve((f1, f2), x, y))
print(f)

1.05: 
(2 - 2*x)*exp(-(x - 1)**2 - (y + 1)**2)
(-2*y - 2)*exp(-(x - 1)**2 - (y + 1)**2)
(2 - 2*x)*(-2*y - 2)*exp(-(x - 1)**2 - (y + 1)**2)
1-6:  [(1, -1)]
exp(-(x - 1)**2 - (y + 1)**2)


In [42]:
#1-7

In [ ]:
#1-8
#1-9
j為根號-1
j平方為-1
由拉恆等式:e**i*pi + 1 = 0
移項: e**i*pi = -1 = j**2
左右都j次放方: (e**j*pi)**j =  (j**2)**j
整理後可得: e**-pi = (j**j)**2 
左右同時開根號 :  j**j =  (1/e**pi)**1/2 = 0.278...

In [50]:
#2-1 ~ 2-7
import numpy as np
A = np.array([[5,1],
            [1,5]])
b = np.array([[10],
            [20]])
print("2.01: ")
print(np.linalg.inv(A)) 
print("2.02: ")
print(A*b) #2-2
print("2.03: ")
print(b*A) #2-3
print("2.04: ")
print(np.transpose(b)*A) 
eigvalue, eigvector = np.linalg.eig(A) 
print("2.05: ")
print(eigvalue,eigvector) 
print("2.07: ")
print(np.linalg.solve(A, b)) 
print("x=1.25,y=3.75代入 5x+y=10 左式等於右式")
print("x=1.25,y=3.75代入 x+5y=20 右式等於右式")

2.01: 
[[ 0.20833333 -0.04166667]
 [-0.04166667  0.20833333]]
2.02: 
[[ 50  10]
 [ 20 100]]
2.03: 
[[ 50  10]
 [ 20 100]]
2.04: 
[[ 50  20]
 [ 10 100]]
2.05: 
[6. 4.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
2.07: 
[[1.25]
 [3.75]]
x=1.25,y=3.75代入 5x+y=10 左式等於右式
x=1.25,y=3.75代入 x+5y=20 右式等於右式
